create table if not exists public.flash_history (
  id bigint generated by default as identity primary key,
  client_id text not null,
  task_id text not null,
  preset_id text not null,
  preset_name text,
  images jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  constraint flash_history_client_task_key unique (client_id, task_id)
);

alter table public.flash_history
  add column if not exists preset_name text;

create index if not exists flash_history_client_created_idx
  on public.flash_history (client_id, created_at desc);

create table if not exists public.flash_presets (
  id text primary key,
  client_id text not null,
  name text not null,
  description text default '',
  theme text default 'custom',
  base_prompt text not null,
  negative_prompt text default '',
  aspect_ratio text not null default '1:1',
  resolution text not null default '1K',
  output_format text not null default 'png',
  variants jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.flash_presets
  add column if not exists negative_prompt text default '';

alter table public.flash_presets
  alter column output_format set default 'png';

create index if not exists flash_presets_client_created_idx
  on public.flash_presets (client_id, created_at asc);
