export const LOCAL_DEFAULT_PRESETS = [
  {
    id: 'local-universel-editorial',
    key: 'universel-editorial',
    name: 'Universel editorial',
    description: "Famille universelle pour produits du quotidien, avec un plan lifestyle contextuel, un plan studio sobre et un plan explosion en apesanteur.",
    theme: 'custom',
    basePrompt: 'The exact same product as in the reference image, with identical shape, identical design, identical colors, identical text and markings fully preserved - do not alter or hallucinate any part of the product. The product placed in a styled flat lay composition on a surface that matches the natural world of this product. Identify what this product is, who uses it, and in what context - then choose surrounding props, materials, textures and atmosphere that are authentically coherent with that world. Props should feel like they naturally coexist with this product in real life. Soft directional natural light, clean composition with breathing space between elements, no hands, no text added, no branding on props, lifestyle editorial photography, photorealistic',
    negativePrompt: 'hands, fingers, face, person, watermark, text added, branding on props, different product, altered shape, altered design, wrong colors, altered label, invented text, hallucinated markings, support structure, cluttered composition',
    aspectRatio: '4:5',
    resolution: '1K',
    outputFormat: 'png',
    variants: [
      {
        id: 'local-universel-editorial-plan-01',
        key: 'plan-01',
        name: 'Flat lay contextuel',
        promptAddon: 'Plan maitre universel.',
        promptOverride: 'The exact same product as in the reference image, with identical shape, identical design, identical colors, identical text and markings fully preserved - do not alter or hallucinate any part of the product. The product placed in a styled flat lay composition on a surface that matches the natural world of this product. Identify what this product is, who uses it, and in what context - then choose surrounding props, materials, textures and atmosphere that are authentically coherent with that world. Props should feel like they naturally coexist with this product in real life. Soft directional natural light, clean composition with breathing space between elements, no hands, no text added, no branding on props, lifestyle editorial photography, photorealistic',
        negativePrompt: 'hands, fingers, face, person, watermark, text added, branding on props, different product, altered shape, altered design, wrong colors, altered label, invented text, hallucinated markings, support structure, cluttered composition',
        aspectRatio: '4:5',
        enabledByDefault: true,
        isMaster: true,
        sourceMode: 'source',
      },
      {
        id: 'local-universel-editorial-plan-02',
        key: 'plan-02',
        name: 'Studio sobre',
        promptAddon: 'Plan produit epure et rassurant.',
        promptOverride: 'The exact same product as in the reference image, with identical shape, identical design, identical colors, identical text and markings fully preserved - do not alter or hallucinate any part of the product. The product placed on a clean surface with soft diffused studio light from slightly above and to the left, neutral background, product in complete sharp focus showing every detail of its material, texture and finish, subtle clean reflection on the surface below, no hands, no text added, no props, product photography, 85mm lens equivalent, photorealistic',
        negativePrompt: 'hands, fingers, face, person, watermark, text added, branding on props, different product, altered shape, altered design, wrong colors, altered label, invented text, hallucinated markings, support structure, cluttered composition',
        aspectRatio: '4:5',
        enabledByDefault: true,
        sourceMode: 'master',
      },
      {
        id: 'local-universel-editorial-plan-03',
        key: 'plan-03',
        name: 'Explosion apesanteur',
        promptAddon: 'Plan campagne dramatique.',
        promptOverride: 'The exact same product as in the reference image, with identical shape, identical design, identical colors, identical text and markings fully preserved - do not alter or hallucinate any part of the product. The product suspended mid-air as if weightless, slightly tilted, label facing camera. Identify what this product contains or is made of - then generate floating elements around it that are physically coherent with its contents or function: liquid droplets, ingredients, particles, sparks, smoke or material fragments matching the product\'s nature. Elements frozen mid-air in all directions around the product, dark background, dramatic rim lighting, no hands, no surface contact, photorealistic, editorial campaign photography',
        negativePrompt: 'hands, fingers, face, person, watermark, text added, branding on props, different product, altered shape, altered design, wrong colors, altered label, invented text, hallucinated markings, surface contact, visible support structure, bright background',
        aspectRatio: '4:5',
        enabledByDefault: true,
        sourceMode: 'master',
      },
    ],
  },
  {
    id: 'local-luxe-pinterest',
    key: 'luxe-pinterest',
    name: 'Luxe Pinterest',
    description: "Pinterest editorial premium en 3 plans : hero universel, bouteille couchee vue de haut, puis verres desires au premier plan.",
    theme: 'premium',
    basePrompt: 'The exact same product as in the reference image, with identical shape, identical proportions, identical design, identical colors, identical materials, identical packaging details, identical text and markings fully preserved and legible - do not alter or hallucinate any part of the product. Create a single luxurious Pinterest-editorial lifestyle image with strong art direction, choosing a decor and styling that are naturally appropriate for this exact product category. First infer what the product is, who buys it, when it is used, and what premium world it belongs to. Then build a coherent scene around it using only refined props, surfaces and background elements that genuinely fit that world: sunlit stone, travertine, terracotta, artisan ceramics, linen, wood, sand, tropical fruit, glassware, resort details, Mediterranean textures, sculptural objects or elegant leisure cues when relevant. Composition must follow the visual proportions of premium Pinterest campaign imagery: portrait framing, layered foreground-midground-background depth, the product large enough to feel hero but never filling the frame, usually occupying around one quarter to one third of the image area, with breathing space around it. Leave elegant negative space, allow some secondary props or body fragments to be partially cropped by the frame edges, and avoid catalog-style centering. Favor placement in the lower-middle or central third with surrounding decor extending beyond the frame so the scene feels like a captured moment inside a larger world. Prefer warm direct sunlight with crisp graphic shadows, rich tactile textures, elevated color harmony and a polished luxury campaign feeling. If human presence makes the scene more desirable and coherent, allow only a cropped body fragment such as a hand, forearm, shoulder or torso fragment, never a face and never a full person. No added text, no branding on props, photorealistic.',
    negativePrompt: 'different product, altered shape, altered proportions, altered design, wrong colors, wrong materials, altered label, altered packaging, invented text, hallucinated markings, watermark, cheap props, supermarket styling, cluttered composition, support structure, low-end packaging, cartoon look, CGI look, blurry product, face, full person, crowd, irrelevant props, corporate studio background, product too small in frame, product filling the whole frame, centered catalog shot, empty dead background, flat composition',
    aspectRatio: '4:5',
    resolution: '1K',
    outputFormat: 'png',
    variants: [
      {
        id: 'local-luxe-pinterest-plan-01',
        key: 'plan-01',
        name: 'Scene universelle Pinterest',
        promptAddon: 'Une seule variante universelle. Le decor doit s adapter intelligemment au produit.',
        promptOverride: 'The exact same product as in the reference image, with identical shape, identical proportions, identical design, identical colors, identical materials, identical packaging details, identical text and markings fully preserved and legible - do not alter or hallucinate any part of the product. Create one premium Pinterest-editorial hero scene tailored specifically to this product. Infer its ideal luxury context from the product itself, then choose a decor, placement, props, surfaces and atmosphere that feel naturally associated with its premium lifestyle world. The visual language should draw from sunlit luxury references: warm direct sunlight, strong elegant shadows, tactile premium materials, resort or Mediterranean influences when relevant, artisan objects, sculptural styling, refined table elements, fruit or ingredient cues, stone, terracotta, linen, sand, wood, water reflections or architectural textures only when coherent with the product. Match the framing logic of high-performing Pinterest luxury still lifes: use portrait composition, build depth in layers, keep the product as the dominant hero while letting it occupy roughly one quarter to one third of the frame instead of filling it, preserve breathing room around the object, and let some secondary elements be partially cropped by the image edges. Position the hero product in a visually intentional way - often slightly below center, in the lower middle third, or anchored centrally with generous headroom - so the surrounding environment feels editorial and expansive. The scene should feel desirable but believable, polished yet natural, never like a sterile packshot. If a human element improves realism, include only a cropped body fragment and never a face or full person. No added text, no branding on props, photorealistic.',
        negativePrompt: 'different product, altered shape, altered proportions, altered design, wrong colors, wrong materials, altered label, altered packaging, invented text, hallucinated markings, cheap props, supermarket styling, cluttered composition, visible support, face, full person, crowd, watermark, irrelevant props, sterile corporate studio, product too small in frame, product filling the whole frame, centered catalog shot, empty dead background, flat composition',
        aspectRatio: '4:5',
        enabledByDefault: true,
        isMaster: true,
        sourceMode: 'source',
      },
      {
        id: 'local-luxe-pinterest-plan-02',
        key: 'plan-02',
        name: 'Bouteille couchee art de vivre',
        promptAddon: 'Bouteille couchee, photo prise du dessus, flat lay charge et premium avec plusieurs verres.',
        promptOverride: 'The exact same bottle or packaged product as in the reference image, with identical shape, identical proportions, identical colors, identical materials, identical packaging details, identical label design and identical text fully preserved and legible - do not alter or hallucinate any part of the product. Restage the product lying down flat on the surface, photographed clearly from above in an overhead flat-lay composition. The bottle should rest horizontally or on a soft diagonal across the scene, never upright. Build a richer Pinterest-editorial arrangement around it with coherent premium elements distributed across the surface: multiple glasses, fruit cuts, garnishes, textiles, ceramics, coasters, serving tools, trays, leisure details or artisanal objects that genuinely match the bottle universe. Match the visual proportions of the references: the bottle is prominent and readable but not oversized, usually occupying about one quarter to one third of the frame, while the surrounding decor fills the rest of the composition in a controlled but abundant way. The styling should feel sunlit, summery, tactile and desirable, with several objects partially cropped by the frame edges so the image feels like a real captured moment instead of a centered catalog shot. Use warm direct sunlight, crisp graphic shadows, premium textures, and a clearly top-down point of view across the whole scene, photorealistic.',
        negativePrompt: 'upright bottle, eye-level shot, frontal shot, perspective side view, isolated packshot, empty scene, cheap party props, supermarket styling, plastic clutter, face, full person, crowd, altered label, invented text, wrong bottle shape, blurry glasses, irrelevant objects, sterile corporate studio, sparse decor, flat generic styling',
        aspectRatio: '4:5',
        enabledByDefault: true,
        sourceMode: 'master',
      },
      {
        id: 'local-luxe-pinterest-plan-03',
        key: 'plan-03',
        name: 'Verres desir premier plan',
        promptAddon: 'Les verres remplis et decores sont au premier plan, la bouteille et l univers soutiennent en fond.',
        promptOverride: 'The exact same bottle or packaged product as in the reference image, with identical shape, identical proportions, identical colors, identical materials, identical packaging details, identical label design and identical text fully preserved and legible - do not alter or hallucinate any part of the product. Create a Pinterest-editorial composition where one or several filled glasses are the foreground heroes, styled according to the exact bottle universe: correct drink color, coherent garnish, rim treatment, fruit, herbs, ice, foam or texture inspired by what the product naturally suggests. The glasses should occupy the front plane prominently, large and seductive, while the bottle appears in the midground or background as a supporting anchor, still recognizable and elegant. Add an immersive decor behind and around them - fruit, bowls, tiles, wood, stone, linen, resort details, serving accessories or atmosphere cues - chosen to match the bottle identity. Follow the visual proportions of premium references: the nearest glass should feel big in frame, the bottle secondary and partially set back, with layered depth and some peripheral objects softly cropped by the edges. Slightly elevated camera angle, not straight-on, warm direct sunlight, crisp highlights and shadows, premium tactile surfaces, photorealistic luxury Pinterest lifestyle photography.',
        negativePrompt: 'empty glasses, bottle as sole hero, incorrect drink color, irrelevant garnish, cheap bar scene, nightclub look, face, full person, crowd, altered label, invented text, wrong bottle shape, flat composition, sterile studio',
        aspectRatio: '4:5',
        enabledByDefault: true,
        sourceMode: 'master',
      },
    ],
  },
  {
    id: 'local-editorial-overlay',
    key: 'editorial-overlay',
    name: 'Editorial Overlay',
    description: "Campagne epuree et stylisee avec vraie zone vide pour texte, univers adapte au produit fourni.",
    theme: 'premium',
    basePrompt: 'The exact same product as in the reference image, with identical shape, identical proportions, identical design, identical colors, identical materials, identical packaging details, identical text and markings fully preserved and legible - do not alter or hallucinate any part of the product. Create a clean, stylized premium editorial campaign image designed to leave intentional space for text overlay. First infer what the product is, who it is for, what premium world it belongs to, and what minimal decor language best supports it. Build a refined scene with a strong visual hierarchy: the hero product or its most natural styled use anchored in the lower half or lower third of the frame, with a large clean negative-space area reserved in the upper area or on one side for future copy. Use a simple tonal background, subtle texture, controlled gradients, sculptural blocks, elegant surfaces or one to three coherent props only when relevant to the product. The image must feel polished, branded and campaign-ready, not empty and not cluttered. Prefer one dominant color world, deliberate spacing, premium materials, and directional light that creates graceful shadows without filling the copy space with noise. Photorealistic.',
    negativePrompt: 'different product, altered shape, altered proportions, altered design, wrong colors, wrong materials, altered label, altered packaging, invented text, hallucinated markings, watermark, cluttered composition, busy patterned background, crowded props, cheap props, supermarket styling, no negative space, copy space blocked, centered catalog shot, flat composition, corporate studio packshot, cartoon look, CGI look, face, full person, crowd',
    aspectRatio: '4:5',
    resolution: '1K',
    outputFormat: 'png',
    variants: [
      {
        id: 'local-editorial-overlay-plan-01',
        key: 'plan-01',
        name: 'Campagne epuree avec texte',
        promptAddon: 'Image stylisee et suffisamment degagee pour ajouter un overlay texte.',
        promptOverride: 'The exact same product as in the reference image, with identical shape, identical proportions, identical design, identical colors, identical materials, identical packaging details, identical text and markings fully preserved and legible - do not alter or hallucinate any part of the product. Create one polished editorial campaign visual with intentional copy space. Infer the ideal premium universe from the product itself, then stage it in a minimal but expressive decor that feels custom to that category. Follow the composition logic of the provided references: keep the hero anchored in the lower half, often on a pedestal, block, tray, tabletop or grounded surface; let the product and supporting styled use occupy roughly one quarter to one third of the frame; and preserve a large calm area in the upper third to upper half, or along one side, with smooth background texture suitable for text overlay. The set should feel stylized rather than generic: one dominant color family, controlled sculptural props, elegant material surfaces, and only a few supporting elements that clarify the universe without clutter. If the product is a bottle, drink, edible item, fragrance or similar lifestyle object, you may include one coherent styled serving, glass, garnish, ingredient or usage cue, but the actual product must stay visible, readable and premium. Lighting should be directional and graphic yet refined, with shadows used to add depth while keeping the text zone clean and usable. Photorealistic, campaign-ready, elevated and spacious.',
        negativePrompt: 'different product, altered shape, altered proportions, altered design, wrong colors, wrong materials, altered label, altered packaging, invented text, hallucinated markings, busy layout, clutter, too many props, product filling the whole frame, product too small, no copy space, blocked text zone, noisy background, centered packshot, flat composition, cheap materials, face, full person, crowd, watermark',
        aspectRatio: '4:5',
        enabledByDefault: true,
        isMaster: true,
        sourceMode: 'source',
      },
    ],
  },
  {
    id: 'local-nouveau-produit',
    key: 'nouveau-produit',
    name: 'Nouveau Produit',
    description: "Serie de lancement premium en 2 plans, ou le produit est la star absolue et tout l'univers visuel est construit a partir de lui.",
    theme: 'premium',
    basePrompt: 'The exact same product as in the reference image, with identical shape, identical proportions, identical design, identical colors, identical materials, identical packaging details, identical label design and identical text and markings fully preserved and legible - do not alter or hallucinate any part of the product. Create a premium new-product launch visual where this product is unquestionably the hero and every decor choice exists only to support it. First infer what the product is, who desires it, what category world it belongs to, and which colors, materials, ingredients, rituals or usage cues are naturally connected to it. Build the entire scene from that logic only: surfaces, props, textures, architecture, ingredients and atmosphere must feel derived from the product itself, never generic or random. Keep the hero product dominant, highly readable and visually celebrated, usually occupying around one quarter to one third of the frame, with layered depth, controlled negative space, refined premium lighting and campaign-level realism. No added text, no branding on props, no competing hero object, photorealistic.',
    negativePrompt: 'different product, altered shape, altered proportions, altered design, wrong colors, wrong materials, altered label, altered packaging, invented text, hallucinated markings, watermark, generic props, irrelevant decor, cluttered composition, product too small, product hidden by props, competing hero object, support structure, cheap styling, supermarket look, flat lighting, cartoon look, CGI look, face, full person, crowd',
    aspectRatio: '4:5',
    resolution: '1K',
    outputFormat: 'png',
    variants: [
      {
        id: 'local-nouveau-produit-plan-01',
        key: 'plan-01',
        name: 'Hero lancement',
        promptAddon: 'Plan maitre. Le produit est la star, l univers entier se construit autour de lui.',
        promptOverride: 'The exact same product as in the reference image, with identical shape, identical proportions, identical design, identical colors, identical materials, identical packaging details, identical label design and identical text and markings fully preserved and legible - do not alter or hallucinate any part of the product. Create a premium new-product launch still life with the product as the undisputed hero. Study the product category and build a restrained editorial composition around it using only a few coherent support elements derived from its own world: one sculptural base, tray, crate, stone block or textured support, plus two to four secondary accents such as ingredients, serving cues or material fragments. The composition must feel highly art directed and spacious, not crowded: portrait framing, product occupying roughly one quarter to one third of the frame height, positioned centrally or slightly lower-center, with generous negative space above and around it. Keep the product the largest, sharpest and most readable element. Supporting objects must feel intentional, balanced and premium, often grouped tightly around the base rather than scattered across the frame. Favor tonal backgrounds, muted but rich color harmony, tactile materials, crisp studio light, clean shadow control and a believable grounded set. No added text, no branding on props, photorealistic.',
        negativePrompt: 'different product, altered shape, altered proportions, altered design, wrong colors, wrong materials, altered label, altered packaging, invented text, hallucinated markings, cluttered scene, too many props, scattered props, generic props, irrelevant decor, centered catalog packshot, product too small, product hidden, competing hero object, cheap styling, supermarket look, face, full person, crowd, watermark',
        aspectRatio: '4:5',
        enabledByDefault: true,
        isMaster: true,
        sourceMode: 'source',
      },
      {
        id: 'local-nouveau-produit-plan-02',
        key: 'plan-02',
        name: 'Reveal sculptural',
        promptAddon: 'Mise en scene graphique et architecturale. Le decor revele le produit au lieu de le concurrencer.',
        promptOverride: 'The exact same product as in the reference image, with identical shape, identical proportions, identical design, identical colors, identical materials, identical packaging details, identical label design and identical text and markings fully preserved and legible - do not alter or hallucinate any part of the product. Build a sculptural reveal image where the set is designed specifically to frame and reveal the product: a carved niche, layered aperture, mineral fissure, monolithic cut-out or architectural silhouette whose form, color and texture are directly inspired by the product. The product must remain dominant, isolated and instantly readable, usually centered and large in frame, with the reveal structure wrapping around it or opening behind it to create a strong halo, window or silhouette effect. Keep the scene minimal and graphic: one dominant reveal device, one clear color world, very few or no extra props, and only small grounded material cues when they genuinely strengthen the story. Favor bold shape language, clean edges, premium surface texture, controlled contrast, precise shadow design and campaign-level lighting. Avoid generic decor and avoid busy storytelling; the power must come from the sculptural framing and the product silhouette itself. No added text, no branding on props, no competing hero object, photorealistic.',
        negativePrompt: 'different product, altered shape, altered label, invented text, random architecture, irrelevant props, clutter, busy background, weak silhouette, product too small, product obscured, too many props, multiple reveal devices, messy set design, support structure, cheap materials, face, full person, crowd, watermark',
        aspectRatio: '4:5',
        enabledByDefault: true,
        sourceMode: 'master',
      },
    ],
  },
];
